AY2223S1-CS2103T-T12-3/tp

README.md

add acknowledgement to README

---

docs/team/zhenglong3.md

Add skeletal PPP for Zheng Long

Add Zheng Long's skeletal PPP

---

docs/DeveloperGuide.md

Update user stories in DG

---

docs/DeveloperGuide.md

Update target user profile in DG

---

docs/DeveloperGuide.md

Add use cases for a few representative user stories to DG

---

docs/UserGuide.md

Update UG for HobbyList v1.2

---

README.md
docs/AboutUs.md
docs/_config.yml

Update project website

---

docs/index.md

Maybe will fix the website adapted thing

Remove traces of AB3 from index.md

---

docs/UserGuide.md

Update UG Features section

---

src/main/java/hobbylist/ui/ActivityCard.java
src/main/resources/view/ActivityListCard.fxml

Different colours for different tags

---

src/main/java/hobbylist/logic/commands/FindTagCommand.java
src/main/java/hobbylist/logic/parser/FindTagCommandParser.java
src/main/java/hobbylist/logic/parser/HobbyListParser.java
src/main/java/hobbylist/model/activity/TagMatchesKeyword.java
src/main/java/hobbylist/model/activity/TagMatchesKeywordPredicate.java
src/main/java/hobbylist/model/tag/Tag.java
src/test/java/hobbylist/logic/commands/FindTagCommandTest.java
src/test/java/hobbylist/logic/parser/FindTagCommandParserTest.java
src/test/java/hobbylist/model/activity/TagMatchesKeywordPredicateTest.java

Add find by tag feature

---

src/main/java/hobbylist/logic/commands/EditCommand.java

Can use edit 1 date/2003-03-03

Fix bugs for edit date

---

src/main/java/hobbylist/commons/core/Messages.java
src/main/java/hobbylist/logic/commands/RateCommand.java
src/main/java/hobbylist/logic/parser/CliSyntax.java
src/main/java/hobbylist/logic/parser/HobbyListParser.java
src/main/java/hobbylist/logic/parser/RateCommandParser.java
src/main/java/hobbylist/model/activity/Activity.java
src/main/java/hobbylist/storage/JsonAdaptedActivity.java
src/main/java/hobbylist/ui/ActivityCard.java
src/main/java/hobbylist/ui/UiManager.java
src/test/java/hobbylist/storage/JsonAdaptedActivityTest.java

User can now rate an activity (1-5).

Add rating

---

src/main/java/hobbylist/logic/commands/FilterStatusCommand.java
src/main/java/hobbylist/logic/parser/FilterStatusCommandParser.java
src/main/java/hobbylist/logic/parser/HobbyListParser.java
src/main/java/hobbylist/model/activity/Status.java
src/main/java/hobbylist/model/activity/StatusMatchesGivenStatus.java

Add filter status command

---

src/main/java/hobbylist/logic/commands/FilterTagCommand.java
src/main/java/hobbylist/logic/parser/FilterTagCommandParser.java
src/main/java/hobbylist/logic/parser/HobbyListParser.java
src/test/java/hobbylist/logic/commands/FilterTagCommandTest.java
src/test/java/hobbylist/logic/parser/FilterTagCommandParserTest.java

Rename FindTag to FilterTag to match the Filter Commands
Close #96

Rename FindTag to FilterTag

---

src/main/java/hobbylist/ui/EditAliasesWindow.java

Commands can be renamed to anything without whitespace

Add validation to rename commands

---

src/main/java/hobbylist/logic/LogicManager.java

Fix unable to rename some commands

---

docs/UserGuide.md
docs/_config.yml
docs/_sass/minima/_layout.scss

Found solution (https://github.com/nus-cs2103-AY2021S1/forum/issues/361) from previous semester's CS2103/T forum 
Can try and see if it works

Remove bullet points from TOC

---

src/main/java/hobbylist/commons/core/Messages.java
src/main/java/hobbylist/logic/commands/FindCommand.java
src/main/java/hobbylist/logic/commands/FindStatusCommand.java
src/main/java/hobbylist/logic/commands/FindTagCommand.java
src/main/java/hobbylist/logic/commands/RateCommand.java

Closes #180, closes #162, closes #153

Fix typo and grammar errors in displayed messages

---

src/main/java/hobbylist/model/activity/Status.java
src/main/java/hobbylist/storage/JsonAdaptedActivity.java

Fix invalid save not being wiped

---

src/main/java/hobbylist/logic/parser/RateCommandParser.java

Detects non integer inputs and displays error message

fix rate non integer inputs

---

docs/team/zhenglong3.md

Added more non-trivial PR reviews

Update Zheng Long PPP
